# Porta del microservizio
server.port=8083

# Nome dell'applicazione
spring.application.name=booking-service

# Configurazione Database PostgreSQL (Adattala alle tue credenziali Docker/Locali)
spring.datasource.url=jdbc:postgresql://localhost:5433/db_booking
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Strategia Hibernate: crea le tabelle in automatico nel DB se non esistono
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true