spring.application.name=communication-service

# --- CONNESSIONE AL DATABASE (Le righe che mancavano) ---
spring.datasource.url=jdbc:postgresql://localhost:5435/communication-service
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Creazione automatica delle tabelle
spring.jpa.hibernate.ddl-auto=update
# Mostra nel terminale le query SQL (molto utile per il debug)
spring.jpa.show-sql=true

# --- RabbitMQ Configuration ---
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

server.port=8084