version: '3.8'

services:
  # Database per il servizio Catalog (il tuo)
  db-catalog:
    image: postgres:15
    container_name: db-catalog
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db_catalog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - travel-network

  # Database per il servizio Booking
  db-booking:
    image: postgres:15
    container_name: db-booking
    ports:
      - "5433:5432" # Porta esterna 5433 per non conflittare con catalog
    environment:
      POSTGRES_DB: db_booking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - travel-network

  # Database per l'Auth (User)
  db-auth:
    image: postgres:15
    container_name: db-auth
    ports:
      - "5434:5432" # Porta esterna 5434
    environment:
      POSTGRES_DB: db_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - travel-network

    # Database per il servizio Communication (Gianmaria)
  communication-service:
    image: postgres:15
    container_name: communication-service
    ports:
      - "5435:5432" # Porta esterna 5435
    environment:
      POSTGRES_DB: communication-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - travel-network

  # RabbitMQ per le comunicazioni asincrone
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Porta per i messaggi
      - "15672:15672" # Interfaccia web di gestione
    networks:
      - travel-network

networks:
  travel-network:
    driver: bridge