### 1. Test di Registrazione
POST http://localhost:8081/api/v1/auth/register
Content-Type: application/json

{
  "email": "dario.elia61@unical.it",
  "password": "password123",
  "role": "ROLE_TRAVELER",
  "name": "Dario2",
  "surname": "Elia2",
  "username": "dario_dev2"
}

### 2. Test di Login
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "dario.elia61@unical.it",
  "password": "password123"
}