# 1. Configurazione del Server
server.port=8081

# 2. Nome del Microservizio
spring.application.name=user-auth-service

# 3. Connessione al Database (Dati allineati al tuo Docker)
# Usiamo la porta 5434 e il nome db_auth come nel file del tuo team
spring.datasource.url=jdbc:postgresql://localhost:5434/db_auth
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# 4. Configurazione JPA / Hibernate
# 'update' crea automaticamente la tabella 'users' se non esiste
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect