spring.application.name=itinerary-service
# Porta definita per il tuo servizio
server.port=8085

# Configurazione PostgreSQL (Seguendo lo standard del collega)
# Nota: usiamo localhost:5435 se seguiamo la progressione dei DB
spring.datasource.url=jdbc:postgresql://localhost:5435/db_itinerary
spring.datasource.username=tuo_username
spring.datasource.password=tua_password

# Importante per i microservizi
spring.jpa.hibernate.ddl-auto=update