spring.application.name=itinerary-service
server.port=8084

# Configurazione PostgreSQL (db_itinerary)
spring.datasource.url=jdbc:postgresql://localhost:5432/db_itinerary
spring.datasource.username=il_tuo_username
spring.datasource.password=la_tua_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true