# ==========================================
# 1. IDENTITÀ DEL MICROSERVIZIO E PORTA
# ==========================================
spring.application.name=catalog-service
server.port=8082 
# (Scegliete una porta fissa per ogni servizio. Es. User=8081, Catalog=8082, Booking=8083)

# ==========================================
# 2. CONFIGURAZIONE DATABASE POSTGRESQL
# ==========================================
# Cambia 'localhost' con il nome del container se usate Docker Compose
spring.datasource.url=jdbc:postgresql://localhost:5432/db_catalog
spring.datasource.username=postgres
spring.datasource.password=${PASSWORD_DB}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# 3. CONFIGURAZIONE JPA E HIBERNATE
# ==========================================
# update: Crea/aggiorna le tabelle in automatico in base alle tue @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# (show-sql e format_sql sono utilissimi ora in fase di sviluppo per vedere le query nel terminale)

# ==========================================
# 4. CONFIGURAZIONE RABBITMQ (Opzionale per ora, ma richiesto dopo)
# ==========================================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest